language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-27.0.3

    # The SDK version used to compile your project
    - android-19
    - android-20
    - android-21
    - android-22
    - android-23
    - android-24
    - android-25
    - android-26
    - android-27

  licenses:
    - 'android-sdk-license-.+'

